options:
  volumes:
    - name: terraform-state
      path: /workspace/terraform
      
steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk  # solo para verificar
    entrypoint: sh
    args:
      - -c
      - |
        if gsutil ls -b gs://${_BUCKET_NAME} >/dev/null 2>&1; then
          echo "Bucket ya existe"
          echo "${_BUCKET_NAME}" > existing_bucket.txt
        fi

  - name: hashicorp/terraform:1.9.5
    entrypoint: sh
    args:
      - -c
      - |
        cd terraform
        terraform init
        if [ -f ../existing_bucket.txt ]; then
          terraform import google_storage_bucket.static_site ${_BUCKET_NAME}
        fi
        terraform apply -auto-approve \
          -var="project_id=${_PROJECT_ID}" \
          -var="region=${_REGION}" \
          -var="bucket_name=${_BUCKET_NAME}"

  - name: gcr.io/cloud-builders/gsutil
    args:
      - -m
      - rsync
      - -r
      - site
      - gs://${_BUCKET_NAME}
